In [3]:
import numpy as np
import random

In [21]:
x   =  np.random.randint(1,10 ,size=(5))
x

array([7, 1, 1, 7, 3])

In [19]:
y = np.random.randint(0,10,size=(5))
y

array([0, 0, 9, 0, 6])

In [22]:
X_b = np.c_[np.ones((10,1)), x]
X_b

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 10 and the array at index 1 has size 5

In [27]:
theta = np.random.randn(1,2)
theta

array([[ 2.4850107 , -0.41691643]])

In [1]:
learning_rate = 0.001
n_iterations = 10000 

In [ ]:
def compute_cost(X,y,theta):
    n = len(y)
    predictions = x.dot(theta)
     

In [ ]:
def gradient_descent(x,y,theta , learning_rate,n_iterations):
    